package internal

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Output formats accepted by Format.
const (
	FormatJSON     = "json"
	FormatNetscape = "netscape"
)

// netscapeHeader is required: the Python cookiejar that yt-dlp, and anything
// else built on http.cookiejar, uses refuses a file without it.
const netscapeHeader = "# Netscape HTTP Cookie File\n# Generated by cutter\n"

// Format renders cookies in the requested output format. Format names are
// matched case insensitively, like browser names.
func Format(cookies []Cookie, format string) (string, error) {
	switch f := strings.ToLower(format); f {
	case "", FormatJSON:
		out, err := json.MarshalIndent(cookies, "", "  ")
		if err != nil {
			return "", err
		}
		return string(out), nil
	case FormatNetscape:
		return netscape(cookies), nil
	default:
		return "", fmt.Errorf("unknown format '%s'. Use '%s' or '%s'", format, FormatJSON, FormatNetscape)
	}
}

// netscape renders the tab separated cookie file that curl, wget and yt-dlp
// read: domain, include subdomains, path, secure, expiry, name, value.
//
// The "#HttpOnly_" domain prefix is a curl extension that the Python cookiejar
// also understands. A leading dot on the domain is what marks a cookie as
// valid for subdomains.
func netscape(cookies []Cookie) string {
	var b strings.Builder
	b.WriteString(netscapeHeader)
	for _, cookie := range cookies {
		domain := cookie.Domain
		if cookie.HttpOnly {
			domain = "#HttpOnly_" + domain
		}

		// A session cookie has no expiry. Go's zero time stands in for that,
		// and the format spells it 0.
		expires := int64(0)
		if !cookie.Expires.IsZero() {
			expires = cookie.Expires.Unix()
		}

		path := cookie.Path
		if path == "" {
			path = "/"
		}

		fmt.Fprintf(&b, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain,
			boolField(strings.HasPrefix(cookie.Domain, ".")),
			path,
			boolField(cookie.Secure),
			expires,
			cookie.Name,
			cookie.Value,
		)
	}
	// The caller adds the final newline, so do not end with a blank line.
	return strings.TrimRight(b.String(), "\n")
}

func boolField(b bool) string {
	if b {
		return "TRUE"
	}
	return "FALSE"
}
